name: Create Production Builds

jobs:
  build_android_apk:
    type: build
    params:
      platform: android
      profile: preview
  build_android_app:
    type: build
    params:
      platform: android
      profile: production
